// config/blockchain.js
// Sets up Ethers.js connection to deployed smart contract

const { ethers } = require('ethers');
const logger     = require('../utils/logger');

// Import the ABI (interface) of our deployed contract
// This file is auto-generated by Hardhat after compilation
const contractABI = require('../../blockchain/artifacts/contracts/NexoraIntegrity.sol/NexoraIntegrity.json').abi;

let contract = null;
let provider = null;
let wallet   = null;

const initBlockchain = async () => {
  try {
    // Connect to Sepolia via Alchemy
    provider = new ethers.JsonRpcProvider(
      process.env.ALCHEMY_SEPOLIA_URL
    );

    // Create wallet from private key
    wallet = new ethers.Wallet(
      process.env.BACKEND_WALLET_PRIVATE_KEY,
      provider
    );

    // Connect to deployed contract
    contract = new ethers.Contract(
      process.env.CONTRACT_ADDRESS,
      contractABI,
      wallet
    );

    logger.info('Blockchain connected: Ethereum Sepolia');
    logger.info(`Contract: ${process.env.CONTRACT_ADDRESS}`);
    logger.info(`Wallet:   ${wallet.address}`);

  } catch (error) {
    logger.error(`Blockchain connection failed: ${error.message}`);
    // Don't crash server if blockchain fails
    // Other features still work
  }
};

// Getter — returns contract instance
const getContract = () => {
  if (!contract) {
    throw new Error('Blockchain not initialized');
  }
  return contract;
};

const getWallet = () => wallet;

module.exports = { initBlockchain, getContract, getWallet };